name: docs build and upload
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  # Documentation build test
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake pandoc xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx jupyter nbconvert sphinx_bootstrap_theme
        pip install -e .

    - name: Build documentation
      run: |
        cd docs
        xvfb-run -a make html
      env:
        READTHEDOCS: "True"
        QT_QPA_PLATFORM: "offscreen"
        DISPLAY: ":99"

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/build/html/

  # Notification job
  notify:
    runs-on: ubuntu-latest
    needs: [docs]
    if: always()

    steps:
    - name: Notify on success
      if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
      run: echo "All jobs completed successfully!"

    - name: Notify on failure
      if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
      run: |
        echo "Some jobs failed or were cancelled"
        exit 1